### ISSUE TITLE
2017.2 Error when compile

### ISSUE THREAD

**Issue by raveneer** [DarrenTsung/DTCompileTimeTracker#10]
version : unity 2017.2
installed : plugins
happen : first time compile

Failed to deserialize CompileTimeKeyframe because splitting by @ did not result in 3 tokens!
UnityEngine.Debug:LogError(Object)
DTCompileTimeTracker.CompileTimeKeyframe:Deserialize(String) (at Assets/Plugins/DTCompileTimeTracker-master/DTCompileTimeTracker-master/CompileTimeTracker/Editor/CompileTimeKeyframe.cs:18)
DTCompileTimeTracker.CompileTimeKeyframe:<DeserializeList>m__0(String) (at Assets/Plugins/DTCompileTimeTracker-master/DTCompileTimeTracker-master/CompileTimeTracker/Editor/CompileTimeKeyframe.cs:42)
System.Linq.Enumerable:ToList(IEnumerable`1)
DTCompileTimeTracker.CompileTimeKeyframe:DeserializeList(String) (at Assets/Plugins/DTCompileTimeTracker-master/DTCompileTimeTracker-master/CompileTimeTracker/Editor/CompileTimeKeyframe.cs:42)
DTCompileTimeTracker.CompileTimeTrackerData:Load() (at Assets/Plugins/DTCompileTimeTracker-master/DTCompileTimeTracker-master/CompileTimeTracker/Editor/CompileTimeTrackerData.cs:51)
DTCompileTimeTracker.CompileTimeTrackerData:.ctor(String) (at Assets/Plugins/DTCompileTimeTracker-master/DTCompileTimeTracker-master/CompileTimeTracker/Editor/CompileTimeTrackerData.cs:29)
DTCompileTimeTracker.CompileTimeTracker:get__Data() (at Assets/Plugins/DTCompileTimeTracker-master/DTCompileTimeTracker-master/CompileTimeTracker/Editor/CompileTimeTracker.cs:29)
DTCompileTimeTracker.CompileTimeTracker:HandleEditorFinishedCompiling() (at Assets/Plugins/DTCompileTimeTracker-master/DTCompileTimeTracker-master/CompileTimeTracker/Editor/CompileTimeTracker.cs:48)
DTCompileTimeTracker.EditorApplicationCompilationUtil:OnEditorUpdate() (at Assets/Plugins/DTCompileTimeTracker-master/DTCompileTimeTracker-master/CompileTimeTracker/Editor/Util/EditorApplicationCompilationUtil.cs:29)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by raveneer** [comment]
only happen first compile. 
from second, compile works well

**Comment by DarrenTsung** [comment]
Sorry for ignoring this issue, I pushed a trivial fix to `master`. Thanks for reporting this!
