### ISSUE TITLE
Failed to deserialize CompileTimeKeyframe because splitting by @ did not result in 3 tokens!

### ISSUE THREAD

**Issue by MigrantP** [DarrenTsung/DTCompileTimeTracker#2]
Running the latest code on Unity 5.3.5f1 on OS X 10.11.5, I got this error immediately after installing the tracker in my project and Unity compiled it:

```
Failed to deserialize CompileTimeKeyframe because splitting by @ did not result in 3 tokens!
UnityEngine.Debug:LogError(Object)
DTCompileTimeTracker.CompileTimeKeyframe:Deserialize(String) (at Assets/CompileTimeTracker/Editor/CompileTimeKeyframe.cs:18)
DTCompileTimeTracker.CompileTimeKeyframe:<DeserializeList>m__4(String) (at Assets/CompileTimeTracker/Editor/CompileTimeKeyframe.cs:42)
System.Linq.Enumerable:ToList(IEnumerable`1)
DTCompileTimeTracker.CompileTimeKeyframe:DeserializeList(String) (at Assets/CompileTimeTracker/Editor/CompileTimeKeyframe.cs:42)
DTCompileTimeTracker.CompileTimeTrackerData:Load() (at Assets/CompileTimeTracker/Editor/CompileTimeTrackerData.cs:49)
DTCompileTimeTracker.CompileTimeTrackerData:.ctor(String) (at Assets/CompileTimeTracker/Editor/CompileTimeTrackerData.cs:29)
DTCompileTimeTracker.CompileTimeTracker:.cctor()
UnityEditor.EditorAssemblies:SetLoadedEditorAssemblies(Assembly[])
```

Subsequent compilations get the same error, but I do also see:

```
Compilation Finished: 22.68s (error)
UnityEngine.Debug:Log(Object)
DTCompileTimeTracker.CompileTimeTrackerWindow:LogCompileTimeKeyframe(CompileTimeKeyframe) (at Assets/CompileTimeTracker/Editor/CompileTimeTrackerWindow.cs:31)
DTCompileTimeTracker.CompileTimeTracker:HandleEditorFinishedCompiling() (at Assets/CompileTimeTracker/Editor/CompileTimeTracker.cs:46)
DTCompileTimeTracker.EditorApplicationCompilationUtil:OnEditorUpdate() (at Assets/CompileTimeTracker/Editor/Util/EditorApplicationCompilationUtil.cs:29)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()
```

The time tracker window shows no information.

I tried creating an empty Unity project and adding the tracker and it seems to work fine there, no errors and data shows up in the window.

**Comment by MigrantP** [comment]
After going back to my main project, I no longer get the error. However, the compile times from the empty project are showing up in the window with my main project. That's really a separate problem so I'll make a new issue for that.

**Comment by DarrenTsung** [comment]
Did you have the old version of the tracker running in your project? It's possible that you then updated and the serialization was switched - leaving old / different formatted data in the editor prefs. 

While you do get that error when failing to parse the tracker information, the next time the tracker saves it should ignore failed data + the data should be clean again.

**Comment by MigrantP** [comment]
I had never had the tracker installed before. The same thing occurred when I first did a build on another machine on the codebase, and then it also went away again. Looks perhaps like a problem with any brand new install.

John
